from polynomial.utils import polynomialRepr
oo = polynomialRepr(2,4)
#oo.generateDict()
print("oooooooo",oo.varNumsPerDeg)
print("varNumUpToDeg",oo.varNumsUpToDeg)
print("listOfMonomials",oo.listOfMonomials)
print("listOfMonomialsPerDeg",oo.listOfMonomialsPerDeg)
print("listOfMonomialsPerDegASINT",oo.listOfMonomialsPerDegAsInt)
print("idxMat",oo.idxMat)
print("listOfMonomialsAsInt",oo.listOfMonomialsAsInt)